### Gazebo-ROS 2 桥接配置
topics:
  # ==================== 传感器数据 (Gazebo→ROS) ====================
  # RGB相机数据
  - topic: /camera/color/image_raw
    gz_topic: /world/default/model/px4vision/link/d435_camera_link/sensor/d435_camera/image
    type: sensor_msgs/msg/Image
    qos:
      reliability: best_effort   # 图像数据允许丢帧
      durability: volatile       # 不保留历史数据
      history: keep_last
      depth: 5                   # 缓冲区大小
      deadline: 33ms             # 30Hz帧率对应时限

  # 深度相机数据
  - topic: /camera/depth/image_raw
    gz_topic: /world/default/model/px4vision/link/d435_camera_link/sensor/d435_depth/depth_image
    type: sensor_msgs/msg/Image
    qos:
      reliability: best_effort
      durability: volatile
      history: keep_last
      depth: 3                   # 深度数据缓冲区减小

  # IMU数据
  - topic: /imu/data
    gz_topic: /world/default/model/px4vision/link/base_link/sensor/imu_sensor/imu
    type: sensor_msgs/msg/Imu
    qos:
      reliability: reliable      # IMU数据需要可靠传输
      durability: volatile
      history: keep_last
      depth: 10
      deadline: 10ms             # 高实时性要求

  # ==================== 控制指令 (ROS→Gazebo) ====================
  # 速度控制指令
  - topic: /drone/cmd_vel
    gz_topic: /model/px4vision/cmd_vel
    type: geometry_msgs/msg/Twist
    qos:
      reliability: reliable
      durability: transient_local # 指令必须持久化
      history: keep_last
      depth: 1                   # 只需要最新指令
      deadline: 10ms             # 控制指令高实时性

  # 电机控制指令（可选）
  - topic: /drone/motor_speed
    gz_topic: /model/px4vision/motor_speed
    type: std_msgs/msg/Float32MultiArray
    qos:
      durability: transient_local
      deadline: 5ms

# ==================== 服务桥接 ====================
services:
  # 模型控制服务
  - gz_service: /world/default/model/px4vision/control
    ros_service: /drone/model_control
    type: ros_gz_interfaces/srv/ControlWorld

  # 传感器配置服务（可选）
  - gz_service: /world/default/model/px4vision/link/d435_camera_link/sensor/d435_camera/change_rate
    ros_service: /drone/camera_rate
    type: ros_gz_interfaces/srv/SetEntityState
