#!/usr/bin/env python3
"""
无人机控制节点可执行脚本
"""

import sys
import os

# 添加项目路径到Python路径
project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(project_dir)

# 添加服务模块路径
install_dir = os.path.dirname(project_dir)
sys.path.append(os.path.join(install_dir, 'local/lib/python3.10/dist-packages'))
sys.path.append(os.path.join(install_dir, 'lib/python3.10/site-packages'))
sys.path.append(os.path.join(install_dir, 'lib/python3.10/dist-packages'))

from drone_control.drone_control_node import main

if __name__ == '__main__':
    main() 